---

- name: Copy elasticsearch exporter script
  ansible.builtin.template:
    src: "es_exporter"
    dest: /usr/local/bin/es_exporter
    mode: 0755
    owner: root
    group: root

- name: Copy elasticsearch exporter script
  ansible.builtin.template:
    src: "es_exporter.service"
    dest: /etc/systemd/system/es_exporter.service
    mode: 0644
    owner: root
    group: root

- name: Restart elasticsearch exporter service is restarted
  ansible.builtin.service:
    name: Es_exporter
    state: restarted
    enabled: true
  changed_when: false

- name: Wait for elasticsearch exporter to become ready
  ansible.builtin.wait_for:
    host: "{{ es_exporter_server_bind }}"
    port: "{{ es_exporter_server_port }}"
    state: started
    delay: 5
    connect_timeout: 15
    timeout: 300
